services:
  app:
    image: ghcr.io/evanston09/forks:main
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: forks
      POSTGRES_PASSWORD: forkspass
      POSTGRES_DB: forks
    volumes:
      - ./storage/docker/psql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forks -d forks"]
      interval: 5s
      timeout: 5s
      retries: 5
